# Generated by Django 3.2.4 on 2023-01-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_worker_wpic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='wpic',
            new_name='pic',
        ),
    ]
